export class UserDashboardView {
    firstName!:string;
    middleName!:string;
    lastName!:string;
    accountNo!:string;
    age!:number;
    gender!:string;
    mobileNo!:string;
    emailId!:string;
    carMake!:string;
    carModel!:string;
    exShowroomPrice!:number;
    loanAmmount!:number;
    loanTenure!:number;
    rateOfInterest!:number;
    uid!:number;
    vId!:number;
    lappid!:number;
    yearlyIncome!:number;
    employmentType!:number;
    existingEmiMonthly!:number;
}
